using System.Collections.Generic;
using Engine.Game.App;
using Engine.Game.App.BaseApp;
using UnityEngine;

public interface IBaseGameCustomController {
    void Awake();
    void broadcastCustomCharacterDataSync();
    void broadcastCustomCharacterDisplayChanged();
    void broadcastCustomCharacterDisplayCodeChanged();
    void broadcastCustomCharacterDisplayNameChanged();
    void broadcastCustomCharacterProfileCodeSync(GameProfileCharacterItem profileCharacterItem = null);
    void broadcastCustomColorsChanged();
    void broadcastCustomColorsPlayerChanged();
    void broadcastCustomColorsSync();
    void broadcastCustomSync();
    GameProfileCustomItem checkCustomColorInit(GameProfileCustomItem customItem, string type);
    bool checkCustomColorPresetExists(string code);
    void directCustom();
    GameProfileCustomItem fillDefaultCustomColors(GameProfileCustomItem customItemTo, string type);
    Color getRandomizedColorFromContext();
    Color getRandomizedColorFromContextCustomized();
    Color getRandomizedColorFromContextEffects();
    Color getRandomizedColorFromContextUI();
    void handlePeriodic();
    void handleSave();
    void handleUpdate();
    void Init();
    GameProfileCustomItem loadColorPresetCustomItem(AppColorPreset preset);
    GameProfileCustomItem loadColorPresetCustomItem(GameProfileCustomItem customItem, AppColorPreset preset);
    void loadCustomColors();
    void OnDisable();
    void OnEnable();
    void run();
    void saveCustomItem();
    void saveCustomItem(GameProfileCustomItem profileCustomItem);
    void setCustomColorsPlayer(GameObject go);
    void setCustomColorsPlayer(GameObject go, GameProfileCustomItem customItem);
    void setMaterialColors(GameObject go, GameProfileCustomItem profileCustomItem);
    void Start();
    void stop();
    void TriggerSave();
    void Update();
    void updateCharacterDisplay(GameObject go, string valName, string valCode);
    void updateCharacterDisplayCode(GameObject go, string val);
    void updateCharacterDisplayName(GameObject go, string val);
    GameProfileCustomItem updateColorPresetObject(GameProfileCustomItem profileCustomItem, GameObject go, string type);
    GameProfileCustomItem updateColorPresetObject(GameProfileCustomItem profileCustomItem, GameObject go, AppColorPreset preset);
    GameProfileCustomItem updateColorPresetObject(GameProfileCustomItem profileCustomItem, GameObject go, string presetType, string presetCode);
    GameProfileCustomItem updateColorPresetObject(GameProfileCustomItem profileCustomItem, GameObject go, string type, Dictionary<string, Color> colors);
    void updateProfileCharacterDisplay(GameObject go);
    void updateProfileCharacterDisplayCode(GameObject go);
    void updateProfileCharacterDisplayName(GameObject go);
    GameProfileCustomItem updateTexturePresetObject(GameProfileCustomItem profileCustomItem, GameObject go, string type);
    GameProfileCustomItem updateTexturePresetObject(GameProfileCustomItem profileCustomItem, GameObject go, AppContentAssetTexturePreset preset);
    GameProfileCustomItem updateTexturePresetObject(GameProfileCustomItem profileCustomItem, GameObject go, string presetType, string presetCode);
}